version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ams-postgres
    environment:
      POSTGRES_USER: ams_user
      POSTGRES_PASSWORD: ams_pwd
      POSTGRES_DB: ams_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: